### ISSUE TITLE
Add upside down mode

### ISSUE THREAD

**Issue by qiemem** [qiemem/eurorack#34]
Requested https://forum.mutable-instruments.net/t/stages-qiemems-alternative-firmware/17506/40 and in the MW thread. pichenettes gives guidance on how to implement: https://forum.mutable-instruments.net/t/stages-qiemems-alternative-firmware/17506/41

**Comment by james-everitt** [comment]
I'm currently using an upside down FW for stages, forked from the original. I just flipped the pin definitions. Will upload to Github over the weekend. Probably beyond my skillset to make it switchable at runtime though! What's the neatest way to merge with your firmware given there will be 2x HEX and WAV files with this approach?

**Comment by qiemem** [comment]
Oh hell yes that's great! How about going ahead and opening a PR with your changes and then we can work together on making the requisite changes to make it configurable on startup (similar to color blind mode)? Does that sound okay?

**Comment by qiemem** [comment]
Hi again @james-everitt; I'd love to include this in the next version. If you open a PR or just post your code somewhere, I should be able to take it from there. Thanks!

**Comment by qiemem** [comment]
The mutable forum is gone, but I was able to find pichenettes guidance on this in a backup I have:

[pichenettes](https://forum.mutable-instruments.net/u/pichenettes) January 27, 2021, 11:29am #41

    Actually found this topic while I was looking for an alternative firmware that allows me to put my stages module upside down. does that exists ?

I am not aware of anyone having developed this, the best way would be to reverse in place all inputs and outputs in the data structure holding a block:
[github.com](https://github.com/pichenettes/eurorack/blob/master/stages/stages.cc#L93)
[pichenettes/eurorack/blob/master/stages/stages.cc#L93](https://github.com/pichenettes/eurorack/blob/master/stages/stages.cc#L93)

    void SysTick_Handler() {
      IWDG_ReloadCounter();
      ui.Poll();
      if (!skip_factory_test) {
        factory_test.Poll();
      }
    }
    }
    IOBuffer::Slice FillBuffer(size_t size) {
      IOBuffer::Slice s = io_buffer.NextSlice(size);
      gate_inputs.Read(s, size);
      if (io_buffer.new_block()) {
        cv_reader.Read(s.block);
        gate_inputs.ReadNormalization(s.block);
      }
      return s;
    }
    SegmentGenerator::Output out[kBlockSize];

Reversing the switches can be handled here:
[github.com](https://github.com/pichenettes/eurorack/blob/master/stages/ui.cc#L80)
[pichenettes/eurorack/blob/master/stages/ui.cc#L80](https://github.com/pichenettes/eurorack/blob/master/stages/ui.cc#L80)

      
      fill(&slider_led_counter_[0], &slider_led_counter_[kNumLEDs], 0);
    }
    void Ui::Poll() {
      system_clock.Tick();
      UpdateLEDs();
      
      switches_.Debounce();
      
      if (chain_state_->ouroboros()) {
        State* s = settings_->mutable_state();
        for (int i = 0; i < kNumSwitches; ++i) {
          if (switches_.pressed(i)) {
            if (press_time_[i] != -1) {
              ++press_time_[i];
            }
            if (press_time_[i] > kLongPressDuration) {
              uint8_t loop_bit = s->segment_configuration[i] & 0x4;
              uint8_t type_bits = s->segment_configuration[i] & 0x03;
              s->segment_configuration[i] = type_bits | (4 - loop_bit);

    second topic I’m wondering if the gate input is ( hardware) designed only for gates, because if it’s just a software issue the module could act as a vca in flashing red mode… and from nor now it actually acts as a vca but only for square lfos !

Yes, the hardware is designed for gates only. ADC channels (with an op-amp to filter and scale the CV input) are more costly!

**Comment by qiemem** [comment]
Added in 0cfa06ee1937cccbd507726b06365f3e701f2cd1
