### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by armandhammer** [qiemem/eurorack#35]
I can't figure out how to download it. The "Download the latest WAV file here" just links back to the top of the page. I don't see any actual download link to a .wav file. Tried on both Chrome and Firefox.

**Comment by qiemem** [comment]
Ah, ya, I suppose that's a little confusing. It's at the bottom of [the release page](https://github.com/qiemem/eurorack/releases/latest):

![image](https://user-images.githubusercontent.com/28215/106089800-93e17f80-60dd-11eb-8d99-9d27f840ed03.png)

Click on the wav file there. Let me know if you have anymore questions!
