### ISSUE TITLE
Dialing in a specific length on TM segments is almost impossible

### ISSUE THREAD

**Issue by qiemem** [qiemem/eurorack#40]
Taking over LEDs while adjusting the pots to display number of steps would much improve the situation.

Switching to 2,3,4,5,6,8,12,16 could also help to, but has obvious downsides.

**Comment by Airell** [comment]
The TM has no implementation for the Button+slider, top, middle, or bottom values.
It might be an option to have it select the number of steps for the Pot:

Top: 2,4,6,8,12,16 steps (2,4,8,16 duplicates of each other, 6 and 12 for polyrythm)
Middle: 2,3,6,10,12,14 steps (3,6,12 duplicates of each other)
Bottom: 5,7,9,11,13,15 steps (the others)
...or any other logical order.

5 values will be much easier to dial in.
