### ISSUE TITLE
Bipolar LEDs on the pot sliders -- possible?

### ISSUE THREAD

**Issue by armandhammer** [qiemem/eurorack#41]
Is it possible to make the pot sliders work with bipolar LEDs? (such as BIVAR R3BC)

Or is it a hardware limitation?

(I tried to ask on the MI forum, but it's been locked in "Read Only" mode for 2+ days now... weird).

**Comment by qiemem** [comment]
The factory LEDs are monochromatic and attempting to set them to other colors in the code does nothing. Or do you mean if you DIY it with bipolar LEDs? I'm not sure, but my guess is it would require modifications to the PCB. Just a heads up that the mutable forum doesn't allow questions about DIY. You might try the DIY section of ModWiggler or something.

> (I tried to ask on the MI forum, but it's been locked in "Read Only" mode for 2+ days now... weird).

I think there's a good chance that it's so it isn't flooded with people freaking out about Behringer's latest bullshit.

**Comment by armandhammer** [comment]
Yeah I just meant pulling the LEDs from the original pots, and sticking R3BC in there and flashing with your firmware to make them show red for negative voltages… if it’s somehow possible to modify the code to make them do that.

**Comment by qiemem** [comment]
Ah I see! Ya, definitely would be a good question for the MI forum, if it were up... Anyway, looking at the driver, I don't believe it would work. AFAICT, the LEDs are controlled with digital outputs, where gradients are achieved through rapid fluctuation of on and off rather than through variable voltages.
