### ISSUE TITLE
Timed Pulse (Red+Gate); Pulse width is at 100% when Pot is at 12 o'clock (50%)

### ISSUE THREAD

**Issue by Airell** [qiemem/eurorack#42]
In Timed Pulse mode, (Red + Gate), the pulse width value is already at 100% when the pot is only at 50% / 12 o'clock.

Observed:
When the pot is at 5 o'clock (CCW / 0%), the pulse width is at 0%.
When the pot is as 11 o'clock, the pulse width is at 50%.
When the pot is at 12 o'clock (50%), the pulse width is 'already' at 100%.
Between 12 o'clock and 7 o'clock (CW), no change, the pulse width keeps being at 100% width.

Expected:
When the pot is at 5 o'clock (CCW / 0%), the pulse width is at 0%.
When the pot is at 12 o'clock (50%), the pulse width is at 50%.
When the pot is at 7 o'clock (CW / 100%,) the pulse width is at 100%.
...and and values between CCW/12 o'clock/CW.

Cheers, Airell.

**Comment by qiemem** [comment]
The pot on timed pulse segments controls the absolute duration of the pulse, not pulse width as a percentage of clock. Fully CW is  16 seconds and fully CCW is about 1ms. 12:00 is .5 seconds. This should be unchanged from stock firmware.

**Comment by Airell** [comment]
Thank you for taking time to look at this and the clarification.
The pulse width is in 'time / duration' and not a direct relation in pot position and width %.
I tested this and I can confirm it works this way. A slower clock/pulse will result in larger pulse widths when pot is beyond 12 0'clock, max ~16 secs.
