### ISSUE TITLE
Will there be a new firmware

### ISSUE THREAD

**Issue by cmoicmodica** [qiemem/eurorack#48]
Hello.

Sorry to post this message here, but since the closure of the Mutables Instruments Forum, I don't know where to find the answers I'm looking for.

Will there be a new firmware for the Stages module, as it was mentioned on the Mutables Instruments Forum?

How can I be informed and follow this progress?

Is there a new forum or something else that has been set up after the disappearance of the official forum?

Thank you very much, have a nice day.

Christophe Modica.

**Comment by qiemem** [comment]
No problem at all! And thank you for your interest! Yes there will be new release merging in the final firmware Émilie released (and the additions made in experimental builds posted [on the mutable forum](https://forum.mutable-instruments.net/t/stages-qiemems-alternative-firmware/17506/200?u=qiemem)). The bulk of the merge is done, but there are several issues that I'd like to solve before doing a real release. Namely:

- No audio-rate clocked oscillators. Like, they'll go to audio rate, but they don't use the specialized audio-rate PLL algorithm as they did before.
- Clocked LFO performance is not good enough yet. **You can't run more than 3 clocked LFOs simultaneously right now.**
- The cool tuner thing where audio rate LFOs blink the closer you are to C only works on free LFOs right now, not clocked LFOs.

The new audio rate oscillators kick in when a ungated green segment is set to bipolar and high frequency. I don't think I'm going to add gated audio rate oscillators; the performance is just too rough, and the original audio rate clocked LFOs were usable at least (though I need to get them working again). 

If interested in trying it out, here's the latest build:

[bipolar-stages-with-final-firmware-experimental-1.zip](https://github.com/qiemem/eurorack/files/10583220/bipolar-stages-with-final-firmware-experimental-1.zip)

As for where to get updates: this repo will get a new release when its ready, and I'll probably put a release announcement on [the modwiggler thread](https://modwiggler.com/forum/viewtopic.php?t=235787), as well as probably the [ModularFirmware](https://www.reddit.com/r/ModularFirmware/) and general [modular](https://www.reddit.com/r/modular) subreddits.

**Comment by qiemem** [comment]
Unfortunately, the forum post with the "experimental build" is no longer available. I *believe* this was latest version posted there. So if you want that much improved random LFO behavior, controllable harmonic ranges in ouroboros mode, but don't want the very experimental merge of the final official firmware, use this. The [cheatsheet](https://github.com/qiemem/eurorack/blob/bipolar/stages/resources/Stages%20Qiemem%20Cheatsheets.pdf) should fully document its behavior.

[stages-bipolar-v1.2.2.zip](https://github.com/qiemem/eurorack/files/10714684/stages-bipolar-v1.2.2.zip)

**Comment by erikhoggard** [comment]
Hello! I just want to echo the sentiment of this post and say thank you for all of your work, Qiemem. It's a shame that the Mutable forums have shut down, but I assure you the hype for this module (and your firmware) hasn't died.

**Comment by timriot** [comment]
I also want to chime in and tell you how much your continued work means to those of us who have come to depend upon this firmware to unlock all of the amazing potential of Stages. Thank you, Qiemem!

**Comment by His-Holy-Noodliness** [comment]
Same, stoked to see there will be a release with the final Mutable changes merged. Much appreciated.

**Comment by bgeorge77** [comment]
Hello folks, I am glad to see this is still an active project from Qiemem. Double Stages with Qiemem is the beating heart of my modular set up. I did a small mod to the Qiemem code, adding a mode in which the POT and SLIDER is switched, allowing for CV control of what used to be the POT value. It's fun, but pretty janky--I have to add in a ton of boundary checks for bad values. I will eventually make a github for it and will let people know here when I do. HOORAH FOR QIEMEM!

**Comment by rafael-azevedo** [comment]
Curious if there are still plans to add 1.2 update features to this firmware.

**Comment by qiemem** [comment]
Unfortunately, I haven't been able to improve the clocked LFO performance sufficiently to feel comfortable putting up a full release, and life circumstances have meant that I have almost no time to work on it these days, and likely won't until the winter. That said, outside of the clocked LFO performance, the firmware linked [in this comment](https://github.com/qiemem/eurorack/issues/48#issuecomment-1416491555) is basically what I've been running for the last few months and has been otherwise pretty stable. So, if you don't anticipate needing to have 4+ clocked LFOs on the same module, then you might consider trying it out!

**Comment by Airell** [comment]
I see the v1.2.2 . zip in this post, this obviously supersedes the 23 dec 2020, but it does not fully implement the official v1.2. Probably you have been pushing the limits of the FW with bi-polar mode v1.1.0, but also did Emilie with official new v1.2 functions. These two now seem hard to merge, Correct?

For me to simply understand, the v1.**2**.2 bi-polar mode could be considered a v1.**1**.2 'development version towards official v1.2 merge' (but at the moment no time develop).

**Comment by qiemem** [comment]
Apologies for the confusion. The version number of this firmware is unrelated to the official version numbers. The v1.2.x line was posted on the MI forum long before the v1.2 of the official firmware. Anyway, to clarify:

- [stages-bipolar-v1.2.2](https://github.com/qiemem/eurorack/files/10714684/stages-bipolar-v1.2.2.zip) is the latest version of the firmware that does *not* include the official v1.2 changes. The only reason I never put a release up for this is I never got around to making the README changes :facepalm: 
- [bipolar-stages-with-final-firmware-experimental-1](https://github.com/qiemem/eurorack/files/10583220/bipolar-stages-with-final-firmware-experimental-1.zip) includes the changes from the official v1.2 firmware. Caveats with this one described above.

**Comment by qiemem** [comment]
Just released [v1.3.0](https://github.com/qiemem/eurorack/releases/tag/v1.3.0)!
