### ISSUE TITLE
clerical error in cheatsheet

### ISSUE THREAD

**Issue by glocke-senda** [qiemem/eurorack#52]
https://github.com/qiemem/eurorack/tree/bipolar/stages#random-segment-type accurately describes the `GR ungated not looping single segment` behavior as stepped/slewed random LFO and the `GR ungated looping` as double scroll. However, the cheatsheet https://github.com/qiemem/eurorack/tree/bipolar/stages#cheatsheet reverses these rows.

Thanks so much for this firmware, I use random segments all the time.

**Comment by qiemem** [comment]
Good catch! Fixed and updated for upcoming release in a5b21c10fd8399ac1636a56f3e3dd6722e2738f6.
