### ISSUE TITLE
Allow control of segment button hold properties without affecting primary properties much

### ISSUE THREAD

**Issue by qiemem** [qiemem/eurorack#6]
See discussion in #1 

In the current version, primary slider/pot functionality is affected when you hold the button down. As of 2eff9aa89b207b9eedf4657d3a950a5a260e2cb9, slider/pot are locked, but the value jumps when the button is released. It would be further nice if there was a way to restore the slider/pot value without it changing much.

Some strategies outlined in #1 include catching the old value (value does not change until the slider/pot returns to its old position) or changing the value as you move the slider up and down in a scaled way to allow the true value to catch up with position. The problem is that interfaces where these strategies are employed typically have another way of indicating true value, whereas the leds in this firmware are already pretty overloaded.

Some alternatives to consider:

- Pause for, say, 1 sec before setting the value to the position. During this time, the user could catch the old value. The downside of this approach is that the value may unexpectedly jump if the user forgets to restore (whereas the jump in the current functionality is more or less expected).
- Gradually slide the value to the position, again, allowing for catching. The downside of this approach is that it would be that the value would always change.

Sliding the value to the position with an accelerating curve could be a nice compromise, but is a bit of a pain to implement (not too bad; just have to actually track time and such like).

**Comment by qiemem** [comment]
@jb0000 any thoughts on preview build of this? Can't decide if it really helps things or if it's too complicated and just jumping on release was good enough. What do you think?

**Comment by jb0000** [comment]
The current preview build of mine has the sliding solution and I like it a lot. In my opinion better than jumping directly. Without clock input it gives a nice little arpeggiating arc when sliding towards the new value. It might not be the most accurate way of dealing with the issue but it put each time it put a a smile on my face.
What do you think?

**Comment by qiemem** [comment]
Awesome. Thanks for the feedback. I'm going to call it good enough for now. 

Also tweaked it so that the LED dimness indicates distance to from locked value to real value so that it brightens as the value is restored. Subtle but gives a nice little indicator of what's going on.

Fixed by 9ae91a27963da79c8376047ca02288c8d4e6db67, 3f39a7dc827c6f4927fc0a3c95177ff2a25500ba, affe0bf3f9ea7cf37d6174940ed446479cd56111, and 6ea73805dc024a8a4ac10901288d5da4a2e4aab7.
